(()=>{'use strict';
const D=window.GAME_DATA,$=id=>document.getElementById(id),$$=q=>[...document.querySelectorAll(q)];
const clamp=n=>Math.max(0,Math.min(100,Math.round(Number(n)||0)));
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Math.round(Number(n)||0));
const uid=()=>globalThis.crypto&&typeof globalThis.crypto.randomUUID==='function'?globalThis.crypto.randomUUID():`${Date.now()}-${Math.random()}`;
const rn=a=>a[Math.floor(Math.random()*a.length)], rand=(a,b)=>a+Math.random()*(b-a);
const eduRank=D.educationRanks||{'None':0,'High School':1,'Trade School':2,'College':3,'Graduate':4};
const AP_MAX=D.rules?.actionPointsPerYear||10;
const F=D.balance.finance,R=D.balance.relationships;
let s=null,eventQueue=[],toastTimer=null;

function npc(name,relation,age,quality=65,gender='Unknown'){return{id:uid(),name,gender,relation,age,quality,alive:true,traits:[rn(D.traits)],career:null,partner:null,children:0,wealth:Math.round(rand(0,25000)),skill:Math.round(rand(25,70))}}
function makeFamily(){return{parents:[npc(rn(D.names.adults),'Parent',Math.floor(rand(25,41)),68),npc(rn(D.names.adults),'Parent',Math.floor(rand(25,43)),68)],siblings:Math.random()<.6?[npc(rn(D.names.children),'Sibling',Math.floor(rand(0,7)),62)]:[],children:[]}}
function hiddenTraits(){return{luck:Math.round(rand(25,85)),longevity:Math.round(rand(35,90)),fertility:Math.round(rand(35,90)),risk:Math.round(rand(15,85))}}
function freshState(name='Player',gender='Male',birthplace='Columbia, SC',background='Balanced',difficulty='Normal'){
  const st={version:D.version,name,gender,birthplace,location:birthplace,background,difficulty,age:0,cash:0,savings:0,debt:0,credit:null,investments:0,
    health:100,happiness:70,intelligence:50,looks:50,fitness:50,social:50,stress:10,karma:50,
    skills:{technology:10,mechanical:10,business:10,communication:10,creativity:10},hidden:hiddenTraits(),
    schoolLevel:'Not started',gpa:null,club:'None',education:'None',major:'None',university:'State University',program:null,programYears:0,programNeed:0,scholarship:0,certifications:[],
    job:null,salary:0,performance:0,jobYears:0,totalYearsWorked:0,company:null,bossQuality:null,lifetimeEarnings:0,taxesPaid:0,jobsHeld:0,
    housing:'parents',inventory:[],relationship:'Single',partner:null,datingPreference:gender==='Male'?'Women':gender==='Female'?'Men':'Anyone',custody:'—',friends:[],family:makeFamily(),
    business:null,criminalRecord:false,jailYears:0,conditions:[],medicalCost:0,lastInvestmentChange:0,lastInvestmentRate:null,lastDebtInterest:0,lastDebtShortfall:0,
    economy:{state:'Normal',inflation:1,marketIndex:1,interest:0.05,housingIndex:1},
    achievements:[],history:[`Age 0: ${name} was born in ${birthplace}.`],pendingConsequences:[],actionPoints:AP_MAX,actionUse:{},settings:{eventFrequency:'normal',confirmRisk:true},
    stats:{highestNetWorth:0,highestSalary:0,childrenRaised:0,crimes:0,businessesStarted:0,homesOwned:0,moves:0},dead:false,deathCause:null,generation:1};
  Object.entries(D.backgrounds[background]?.mods||{}).forEach(([k,v])=>{if(k in st)st[k]+=v});return st;
}
function normalize(raw){
  const b=freshState(raw?.name||'Player',raw?.gender||'Male',raw?.birthplace||'Columbia, SC',raw?.background||'Balanced',raw?.difficulty||'Normal');
  const m={...b,...raw,actionPoints:Number.isFinite(raw?.actionPoints)?raw.actionPoints:AP_MAX,actionUse:{...(raw?.actionUse||{})},skills:{...b.skills,...(raw?.skills||{})},hidden:{...b.hidden,...(raw?.hidden||{})},economy:{...b.economy,...(raw?.economy||{})},settings:{...b.settings,...(raw?.settings||{})},stats:{...b.stats,...(raw?.stats||{})},family:{...b.family,...(raw?.family||{})}};
  ['parents','siblings','children'].forEach(k=>m.family[k]=Array.isArray(m.family[k])?m.family[k]:[]);['inventory','friends','certifications','conditions','achievements','history','pendingConsequences'].forEach(k=>m[k]=Array.isArray(m[k])?m[k]:[]);return m;
}
function slotKey(slot){return`${D.saveKey}:slot:${slot}`}
function saveAutosave(show=false){try{localStorage.setItem(`${D.saveKey}:auto`,JSON.stringify(s));$('autosaveStatus').textContent='Saved';if(show)msg('saveMessage','Game saved.')}catch(e){$('autosaveStatus').textContent='Save unavailable'}}
function loadAutosave(){try{let raw=localStorage.getItem(`${D.saveKey}:auto`);if(!raw){for(const k of D.legacyKeys){raw=localStorage.getItem(k);if(raw)break}}if(!raw)return false;s=normalize(JSON.parse(raw));return true}catch{return false}}
function saveSlot(slot){try{localStorage.setItem(slotKey(slot),JSON.stringify(s));msg('slotMessage',`Saved to Slot ${slot}.`)}catch{msg('slotMessage','Unable to save slot.')}}
function loadSlot(slot){try{const raw=localStorage.getItem(slotKey(slot));if(!raw)return msg('slotMessage',`Slot ${slot} is empty.`);s=normalize(JSON.parse(raw));eventQueue=[];msg('slotMessage',`Loaded Slot ${slot}.`);commit()}catch{msg('slotMessage','Unable to load slot.')}}
function log(text){
  if(!text)return;
  const line=/^Age\s+\d+:/i.test(text)?text:`Age ${s.age}: ${text}`;
  s.history.push(line);
  const limit=D.rules?.historyLimit||900;if(s.history.length>limit)s.history=s.history.slice(-limit);
}
function historyGroups(){
  const groups=new Map();
  for(const raw of s.history){
    const line=String(raw||'');
    const m=line.match(/^Age\s+(\d+):\s*(.*)$/i);
    const age=m?Number(m[1]):0, text=m?m[2]:line;
    if(!groups.has(age))groups.set(age,[]);
    groups.get(age).push(text);
  }
  return [...groups.entries()].sort((a,b)=>b[0]-a[0]).slice(0,(D.rules?.historyYearsVisible||35));
}
function renderHistory(){
  const el=$('log');
  el.innerHTML=historyGroups().map(([age,items])=>`<section class=\"year-log\"><h3>Age: ${age} ${age===1?'year':'years'}</h3><div class=\"year-events\">${items.map(x=>`<div class=\"log-entry\">${escapeHtml(x)}</div>`).join('')}</div></section>`).join('');
  requestAnimationFrame(()=>{el.scrollTop=0});
}
function ambientYear(){
  const pools=[];
  if(s.age<5)pools.push('I spent time playing at home.','I learned something new about the world.','My family spent time with me.');
  else if(s.age<11)pools.push('I had an ordinary day at elementary school.','I played outside after school.','I talked with my family about my day.','I spent time on a hobby.');
  else if(s.age<14)pools.push('I navigated another year of middle school.','I spent time with classmates.','I worked on school assignments.','I thought about what I might want to do when I grow up.');
  else if(s.age<18)pools.push('I made it through another year of high school.','I spent time with friends after school.','I thought about life after graduation.','I dealt with the usual pressures of being a teenager.');
  else if(s.age<65)pools.push('Another year of adult life passed.','I took care of everyday responsibilities.','I thought about my goals for the future.');
  else pools.push('I reflected on another year of life.','I spent more time thinking about family and the years behind me.','I tried to take things at a comfortable pace.');
  if(s.job)pools.push(`I continued working at ${s.company}.`);
  if(s.partner)pools.push(`I spent time with ${s.partner.name}.`);
  if(s.family.children.some(c=>c.alive&&c.age<18))pools.push('I spent time raising my children.');
  const count=Math.min(pools.length,Math.random()<.35?2:1), used=new Set();
  for(let i=0;i<count;i++){let x=rn(pools);while(used.has(x)&&used.size<pools.length)x=rn(pools);used.add(x);log(x)}
}
function toast(text){const t=$('toast');t.textContent=text;t.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.add('hidden'),1900)}
function stat(k,d){if(k in s.skills){s.skills[k]=clamp(s.skills[k]+d);return}if(['cash','savings','debt','investments','salary','scholarship'].includes(k)){s[k]=Math.max(0,(s[k]||0)+d);return}s[k]=clamp((s[k]||0)+d)}
function actionCost(key,cost=1){if(s.dead)return false;if((s.actionPoints??0)<cost){toast('No Action Points left this year. Age up to refresh them.');return false}s.actionPoints-=cost;s.actionUse[key]=(s.actionUse[key]||0)+1;return true}
function actionMultiplier(key){const n=s.actionUse[key]||1;const curve=D.rules?.diminishingReturns||[1,.6,.3,.1];return curve[Math.min(n-1,curve.length-1)]??curve[curve.length-1]}
function scaled(v,key){return v<0?v:Math.max(1,Math.round(v*actionMultiplier(key)))}
function pathValue(path){return String(path||'').split('.').reduce((v,k)=>v==null?undefined:v[k],s)}
function metricValue(name){if(name==='netWorth')return netWorth();if(name==='businessValue')return businessValue();if(name==='homeOwned')return !!D.housing[s.housing]?.owned;if(name==='familyAlive')return [...s.family.parents,...s.family.siblings].some(p=>p.alive);if(name==='hasLivingChild')return s.family.children.some(p=>p.alive);return undefined}
function requirementMissing(req){
  if(!req)return null;const v=req.value,label=req.label;
  switch(req.type){
    case'ageMin':return s.age>=v?null:(label||`Age ${v}+`);
    case'educationMin':return (eduRank[s.education]||0)>=(eduRank[v]||0)?null:(label||v);
    case'intelligenceMin':return s.intelligence>=v?null:(label||`Intelligence ${v}+`);
    case'socialMin':return s.social>=v?null:(label||`Social ${v}+`);
    case'skillMin':return (s.skills[req.skill]||0)>=v?null:(label||`${req.skill[0].toUpperCase()+req.skill.slice(1)} ${v}+`);
    case'cashMin':return s.cash>=v?null:(label||`${money(v)} cash`);
    case'creditMin':return (s.credit??0)>=v?null:(label||`Credit ${v}+`);
    case'notJailed':return s.jailYears<=0?null:(label||'Not while jailed');
    case'hasPartner':return !!s.partner?null:(label||'Relationship required');
    case'noPartner':return !s.partner?null:(label||'Must be single');
    case'relationshipIs':return s.relationship===v?null:(label||`${v} relationship`);
    case'partnerAgeMin':return s.partner&&s.partner.age>=v?null:(label||`Partner age ${v}+`);
    case'partnerQualityMin':return s.partner&&s.partner.quality>=v?null:(label||`Relationship quality ${v}+`);
    case'programNone':return !s.program?null:(label||'Finish current program first');
    case'arrayLengthMin':{const a=pathValue(req.path);return Array.isArray(a)&&a.length>=v?null:(label||`${v}+ ${req.path}`)}
    case'valueMin':return Number(pathValue(req.path)||0)>=v?null:(label||`${req.path} ${v}+`);
    case'valueMax':return Number(pathValue(req.path)||0)<=v?null:(label||`${req.path} ${v} or less`);
    case'valueEquals':return pathValue(req.path)===v?null:(label||`${req.path}: ${v}`);
    case'truthy':return !!pathValue(req.path)?null:(label||req.path);
    case'metricMin':return Number(metricValue(req.metric)||0)>=v?null:(label||`${req.metric} ${v}+`);
    case'metricTruthy':return !!metricValue(req.metric)?null:(label||req.metric);
    default:return null;
  }
}
function missingRequirements(requirements=[]){return requirements.map(requirementMissing).filter(Boolean)}
function meetsRequirements(requirements=[]){return missingRequirements(requirements).length===0}
function jobMissing(j){return missingRequirements(j.requirements||[])}
function refreshJobOptions(){const sel=$('jobSelect'),value=sel.value;sel.innerHTML='';Object.entries(D.jobs).forEach(([k,j])=>{const miss=jobMissing(j),o=new Option(`${miss.length?'🔒 ':''}${j.name} — ${money(jobSalary(j))}`,k);o.dataset.locked=miss.length?'1':'0';sel.add(o)});if([...sel.options].some(o=>o.value===value))sel.value=value;showJobRequirements()}
function showJobRequirements(){const j=D.jobs[$('jobSelect').value];if(!j)return;const miss=jobMissing(j);$('jobRequirements').innerHTML=miss.length?`<span class="locked-text">🔒 Locked — ${escapeHtml(miss.join(' • '))}</span>`:'<span class="unlocked-text">✓ You meet the requirements for this job.</span>'}
function applyNeglect(){const u=s.actionUse||{};if(s.age>=5&&s.age<18&&!u.schoolStudy){s.gpa=Math.max(0,(s.gpa||0)-.08);log('I did not put much effort into school this year.')}if(s.partner&&!u.partnerTime){s.partner.quality=clamp(s.partner.quality-4);log(`I did not make much time for ${s.partner.name} this year.`)}const familyAlive=[...s.family.parents,...s.family.siblings,...s.family.children].some(x=>x.alive);if(familyAlive&&!u.familyTime){[...s.family.parents,...s.family.siblings,...s.family.children].filter(x=>x.alive).forEach(x=>x.quality=clamp(x.quality-2));}if(s.age>=12&&!u.exercise){stat('fitness',-2)}if(s.job&&!u.work&&!u.network){stat('performance',-3)}}
function stage(){return (D.lifeStages||[]).find(x=>s.age<=x.maxAge)?.label||'Senior'}
function location(){return D.locations[s.location]||D.locations['Columbia, SC']}
function diff(){return D.difficulties[s.difficulty]||D.difficulties.Normal}
function inventoryValue(){return s.inventory.reduce((sum,x)=>sum+x.value,0)}
function homeValue(){const h=D.housing[s.housing];return h?.owned?(h.price*s.economy.housingIndex):0}
function businessValue(){if(!s.business)return 0;return Math.max(0,Math.round((s.business.cash||0)+(s.business.revenue||0)*2.2+(s.business.employees||0)*7500+(s.business.reputation||50)*500))}
function netWorth(){return Math.round(s.cash+s.savings+s.investments+inventoryValue()+homeValue()+businessValue()-s.debt)}
function annualExpenses(){if(s.age<18)return 0;const h=D.housing[s.housing]||D.housing.parents;const childCost=s.family.children.filter(x=>x.alive&&x.age<18).length*6500;const baseAmount=s.housing==='parents'?(D.rules?.livingWithParentsBase||3000):12000;const base=baseAmount*location().cost*s.economy.inflation;return Math.round((base+h.annual*location().housing+childCost+s.medicalCost)*diff().expense)}
function jobSalary(j){return Math.round(j.salary*location().wage*s.economy.inflation)}
function makeProgress(label,val){return`<div class="stat"><div class="stat-head"><span>${label}</span><strong>${Math.round(val)}</strong></div><div class="meter"><i style="width:${clamp(val)}%"></i></div></div>`}
function achievementTest(a){return meetsRequirements(a.requirements||[])}
function checkAchievements(){for(const a of D.achievements){if(!s.achievements.includes(a.id)&&achievementTest(a)){s.achievements.push(a.id);log(`Age ${s.age}: Achievement unlocked — ${a.name}.`);toast(`🏆 ${a.name}`)}}}
function updateStats(){const nw=netWorth();s.stats.highestNetWorth=Math.max(s.stats.highestNetWorth,nw);s.stats.highestSalary=Math.max(s.stats.highestSalary,s.salary||0)}
function commit(){checkAchievements();updateStats();render();saveAutosave()}
function msg(id,text){const el=$(id);if(el)el.textContent=text}
function canAdult(){return s.age>=(D.rules?.adultAge||18)&&!s.dead&&s.jailYears<=0}
function occupationLabel(){
  if(s.jailYears>0)return `Incarcerated • ${s.jailYears} yr${s.jailYears===1?'':'s'} remaining`;
  if(s.age>=5&&s.age<18)return s.schoolLevel&&s.schoolLevel!=='Not started'?`${s.schoolLevel} Student`:'Student';
  if(s.program)return `${s.program}${s.major&&s.major!=='None'?` • ${s.major}`:''}`;
  if(s.job)return `${D.jobs[s.job]?.name||'Employed'}${s.company?` • ${s.company}`:''}`;
  if(s.age<5)return stage();
  return 'Unemployed';
}
function avatarLetter(){const n=(s.name||'P').trim();return (n[0]||'P').toUpperCase()}

function render(){
  const occ=occupationLabel(),ap=Math.max(0,Math.min(AP_MAX,s.actionPoints ?? AP_MAX));
  $('ageVal').textContent=s.age;$('stageVal').textContent=stage();$('actionsVal').textContent=`${ap}/${AP_MAX}`;$('headerAP').textContent=`${ap}/${AP_MAX}`;$('cashVal').textContent=money(s.cash);$('worthVal').textContent=`${money(netWorth())} net worth`;$('locationVal').textContent=s.location;$('economyVal').textContent=s.economy.state;
  $('headerName').textContent=s.name;$('headerRole').textContent=occ;$('headerCash').textContent=money(s.cash);$('homeNameVal').textContent=s.name;$('homeRoleVal').textContent=occ;$('avatarVal').textContent=avatarLetter();
  $('actionDots').innerHTML=Array.from({length:AP_MAX},(_,i)=>`<i class="action-dot${i<ap?' on':''}"></i>`).join('');
  $('statsGrid').innerHTML=['happiness','health','intelligence','looks'].map(k=>makeProgress(k==='intelligence'?'Smarts':k[0].toUpperCase()+k.slice(1),s[k])).join('');
  if($('allStatsGrid'))$('allStatsGrid').innerHTML=['health','happiness','intelligence','looks','fitness','social','stress','karma'].map(k=>makeProgress(k[0].toUpperCase()+k.slice(1),s[k])).join('');
  $('skillsGrid').innerHTML=Object.entries(s.skills).map(([k,v])=>makeProgress(k[0].toUpperCase()+k.slice(1),v)).join('');
  $('conditionsVal').textContent=s.conditions.length?s.conditions.map(c=>c.name).join(', '):'None';$('medicalVal').textContent=money(s.medicalCost);
  renderHistory();
  $('datingPreferenceSelect').value=s.datingPreference||'Anyone';
  $('schoolVal').textContent=s.schoolLevel;$('gpaVal').textContent=s.gpa===null?'—':s.gpa.toFixed(2);$('clubVal').textContent=s.club;$('eduVal').textContent=s.education;$('majorVal').textContent=s.major;$('scholarshipVal').textContent=money(s.scholarship);$('eduProgress').textContent=s.program?`${s.program} ${s.programYears}/${s.programNeed}`:'—';renderEducationCostPreview();
  $('certList').innerHTML=s.certifications.length?s.certifications.map(x=>`<span class="chip">${escapeHtml(x)}</span>`).join(''):'<span class="muted">No certifications yet.</span>';
  refreshJobOptions();const j=s.job?D.jobs[s.job]:null;$('jobVal').textContent=j?.name||'None';$('companyVal').textContent=s.company||'—';$('salaryVal').textContent=money(s.salary);$('performanceVal').textContent=Math.round(s.performance);$('experienceVal').textContent=`${s.jobYears||0} yrs`;$('bossVal').textContent=s.bossQuality===null?'—':Math.round(s.bossQuality);
  $('cash2Val').textContent=money(s.cash);$('savingsVal').textContent=money(s.savings);$('debtVal').textContent=money(s.debt);$('debtRateVal').textContent=`${(s.economy.interest*100).toFixed(1)}%`;$('debtInterestVal').textContent=s.lastDebtInterest?`+${money(s.lastDebtInterest)}`:money(0);$('creditVal').textContent=s.credit===null?'—':Math.round(s.credit);$('investVal').textContent=money(s.investments);$('investmentReturnVal').textContent=s.lastInvestmentRate===null?'—':`${s.lastInvestmentChange>=0?'+':''}${money(s.lastInvestmentChange)} (${s.lastInvestmentRate>=0?'+':''}${(s.lastInvestmentRate*100).toFixed(1)}%)`;$('investmentReturnVal').className=s.lastInvestmentRate===null?'':s.lastInvestmentChange>=0?'positive':'negative';$('expensesVal').textContent=money(annualExpenses());$('housingVal').textContent=D.housing[s.housing]?.name||s.housing;
  $('inventoryList').innerHTML=s.inventory.length?s.inventory.map(i=>`<div class="item-row"><div><strong>${escapeHtml(i.name)}</strong><div class="person-meta">${escapeHtml(i.type)} • Condition ${Math.round(i.condition)}%</div></div><strong>${money(i.value)}</strong></div>`).join(''):'<p class="muted">Nothing notable owned.</p>';
  $('businessVal').textContent=s.business?s.business.name:'None';$('businessValueVal').textContent=money(businessValue());$('employeesVal').textContent=s.business?.employees||0;$('businessRepVal').textContent=s.business?Math.round(s.business.reputation):'—';
  $('relationshipVal').textContent=s.relationship;$('partnerVal').textContent=s.partner?.name||'—';$('relationshipQuality').textContent=s.partner?Math.round(s.partner.quality):'—';$('custodyVal').textContent=s.custody||'—';
  $('familyList').innerHTML=[...s.family.parents,...s.family.siblings].map(personRow).join('')||'<p class="muted">No family listed.</p>';
  $('childrenList').innerHTML=s.family.children.map(personRow).join('')||'<p class="muted">No children.</p>';$('friendsList').innerHTML=s.friends.map(personRow).join('')||'<p class="muted">No close friends.</p>';
  $('recordVal').textContent=s.criminalRecord?'Criminal record':'Clean';$('jailVal').textContent=s.jailYears>0?`${s.jailYears} year(s) remaining`:'No';
  $('achievementsVal').innerHTML=s.achievements.length?s.achievements.map(id=>{const a=D.achievements.find(x=>x.id===id);return`<span class="chip" title="${escapeHtml(a?.description||'')}">🏆 ${escapeHtml(a?.name||id)}</span>`}).join(''):'<span class="muted">No achievements yet.</span>';
  $('lifetimeStats').innerHTML=lifetimeStatsHtml();
  $('eventFreqSelect').value=s.settings.eventFrequency;$('confirmRiskSelect').value=s.settings.confirmRisk?'yes':'no';
  const disabled=s.dead; $('ageBtn').disabled=disabled;$$('button[data-ap]').forEach(b=>b.disabled=disabled);
  const investNeed=missingRequirements(F.invest.requirements||[]);$('investBtn').disabled=disabled||investNeed.length>0;if(investNeed.length)msg('investmentMessage',`Locked: ${investNeed.join(' • ')}.`);
  $('sellInvest1000Btn').disabled=disabled||s.investments<1000;$('sellInvest25Btn').disabled=disabled||s.investments<=0;$('sellInvestAllBtn').disabled=disabled||s.investments<=0;
  const supportKids=s.family.children.filter(x=>x.alive&&x.age<18);$('childSupportBtn').disabled=disabled||!supportKids.length||s.cash<R.childSupport.cost||(s.actionPoints??0)<R.childSupport.ap;
  if(!supportKids.length)msg('childSupportMessage',`Locked: You don't have children to support.`);else if(s.cash<R.childSupport.cost)msg('childSupportMessage',`Locked: Need ${money(R.childSupport.cost)} cash.`);else if((s.actionPoints??0)<R.childSupport.ap)msg('childSupportMessage',`Locked: Need ${R.childSupport.ap} AP.`);else msg('childSupportMessage','');
  $('studySchoolBtn').disabled=s.age<5||s.age>=18||disabled;$$('#schoolClubActions button').forEach(b=>b.disabled=s.age<5||s.age>=18||disabled||((s.actionPoints??0)<Number(b.dataset.ap||1)));
  ['tradeBtn','collegeBtn','gradBtn','dropoutBtn','certBtn','applyBtn','workBtn','networkBtn','promotionBtn','quitBtn','loanBtn','bankruptcyBtn','housingBtn','startBusinessBtn','hireBtn','upgradeBusinessBtn','sellBusinessBtn','businessBankruptcyBtn','dateBtn','partnerTimeBtn','giftBtn','argueBtn','proposeBtn','marryBtn','breakupBtn','childBtn','crimeBtn','moveBtn'].forEach(id=>$(id).disabled=disabled);
  $('workBtn').disabled=disabled||!s.job||s.jailYears>0;$('networkBtn').disabled=disabled||!s.job||s.jailYears>0;$('promotionBtn').disabled=disabled||!s.job||s.jailYears>0;$('quitBtn').disabled=disabled||!s.job;
  $('payDebtBtn').disabled=disabled||s.debt<=0||s.cash<=0;$('payDebt10000Btn').disabled=disabled||s.debt<=0||s.cash<=0;$('payDebt25Btn').disabled=disabled||s.debt<=0||s.cash<=0;$('payDebtAllBtn').disabled=disabled||s.debt<=0||s.cash<=0;
  $$('button[data-ap]').forEach(b=>{const cost=Number(b.dataset.ap||1);if((s.actionPoints??0)<cost)b.disabled=true});
}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function personRow(p){const q=p.alive?clamp(p.quality):0;return`<div class="person-row"><div><strong>${escapeHtml(p.name)} <span class="relation-label">(${escapeHtml(p.relation)})</span></strong><div class="person-meta">Age ${p.age}${p.alive?'':' • Deceased'}${(p.traits||[]).length?` • ${escapeHtml(p.traits.join(', '))}`:''}</div>${p.alive?`<div class="relationship-bar"><i style="width:${q}%"></i></div>`:''}</div><strong>${p.alive?`${q}%`:'—'}</strong></div>`}
function lifetimeStatsHtml(){const pairs=[['Generation',s.generation],['Lifetime earnings',money(s.lifetimeEarnings)],['Taxes paid',money(s.taxesPaid)],['Highest salary',money(s.stats.highestSalary)],['Highest net worth',money(s.stats.highestNetWorth)],['Jobs held',s.jobsHeld],['Years worked',s.totalYearsWorked],['Children',s.family.children.length],['Moves',s.stats.moves],['Crimes attempted',s.stats.crimes],['Businesses started',s.stats.businessesStarted],['Current net worth',money(netWorth())]];return pairs.map(([a,b])=>`<span>${a}</span><strong>${b}</strong>`).join('')}

function schoolYear(){const y=D.balance.yearly.school;if(s.age===5){s.schoolLevel='Elementary School';s.gpa=2.6;log('Age 5: You started elementary school.')}if(s.age===11){s.schoolLevel='Middle School';log('Age 11: You started middle school.')}if(s.age===14){s.schoolLevel='High School';log('Age 14: You started high school.')}if(s.age>=5&&s.age<18&&s.gpa!==null){s.gpa=Math.max(0,Math.min(4,s.gpa+rand(...y.gpaDrift)+(s.intelligence-50)/y.intelligenceWeight-(s.stress-40)/y.stressWeight));}if(s.age===18){s.schoolLevel='Graduated';if((s.gpa||0)>=1.8){s.education='High School';log(`Age 18: You graduated high school with a ${s.gpa.toFixed(2)} GPA.`)}else log('Age 18: You did not graduate high school.');if(s.credit===null)s.credit=650}}
function educationYear(){if(!s.program)return;const y=D.balance.yearly.school;s.programYears++;stat('stress',y.educationStress);const uni=s.program==='College'||s.program==='Graduate School'?(D.universities[s.university]||D.universities['State University']):{learning:1,tuition:1};stat('intelligence',y.educationIntelligence*uni.learning);const tuition=Math.max(0,s.programAnnualCost*uni.tuition-(s.scholarship||0));if(tuition>0){const pay=Math.min(s.cash,tuition);s.cash-=pay;s.debt+=tuition-pay}s.scholarship=0;if(s.programYears>=s.programNeed){s.education=s.program==='Graduate School'?'Graduate':s.program;if(s.major!=='None'){const m=D.majors[s.major];if(m){if(m.skill==='intelligence')stat('intelligence',m.bonus);else stat(m.skill,m.bonus)}}log(`Age ${s.age}: Completed ${s.program}${s.major!=='None'?` in ${s.major}`:''}.`);s.program=null;s.programYears=0;s.programNeed=0;s.programAnnualCost=0}}
function economyYear(){const y=D.balance.yearly.economy,roll=Math.random();if(roll<y.recessionChance)s.economy.state='Recession';else if(roll>y.boomThreshold)s.economy.state='Boom';else s.economy.state='Normal';const state=s.economy.state,inflationRate=rand(...y.inflation[state]);s.economy.inflation*=1+inflationRate;s.economy.marketIndex*=rand(...y.market[state]);s.economy.housingIndex*=rand(...y.housing[state]);s.economy.interest=rand(...y.interest[state])}
function careerYear(){const y=D.balance.yearly.career;if(s.jailYears>0){s.jailYears--;stat('happiness',y.jailHappiness);stat('stress',y.jailStress);if(s.jailYears===0)log(`Age ${s.age}: You were released from jail.`);return}if(s.job){s.jobYears++;s.totalYearsWorked++;const gross=s.salary,tax=gross*location().tax,net=gross-tax,expenses=annualExpenses();s.cash+=net-expenses;s.lifetimeEarnings+=gross;s.taxesPaid+=tax;stat('performance',-y.performanceDecay);stat('stress',y.stressGain);s.bossQuality=clamp((s.bossQuality??50)+rand(...y.bossDrift));const layoffChance=(y.layoffChance[s.economy.state]??y.layoffChance.Normal)*diff().layoff;if(Math.random()<layoffChance&&s.performance<y.layoffPerformanceThreshold){log(`Age ${s.age}: You were laid off from ${s.company}.`);s.job=null;s.salary=0;s.performance=0;s.company=null;s.bossQuality=null;stat('stress',10)}else if(s.performance<y.firePerformanceThreshold&&Math.random()<y.fireChance){log(`Age ${s.age}: You were fired for poor performance.`);s.job=null;s.salary=0;s.performance=0;s.company=null;s.bossQuality=null;stat('stress',12)}}else if(s.age>=18){s.cash-=annualExpenses();stat('happiness',y.unemployedHappiness);stat('stress',y.unemployedStress)}}
function financeYear(){const y=D.balance.yearly.finance,home=D.housing[s.housing];if(home?.owned)stat('happiness',1);else if(s.housing==='apartment')stat('happiness',0);s.lastDebtInterest=0;s.lastDebtShortfall=0;if(s.debt>0){const beforeDebt=s.debt;s.debt*=1+s.economy.interest;s.lastDebtInterest=Math.round(s.debt-beforeDebt);if(s.lastDebtInterest>0)log(`My outstanding debt accrued ${money(s.lastDebtInterest)} in interest this year.`);if(s.credit!==null)s.credit=Math.max(300,s.credit-y.debtCreditPenalty)}if(s.savings>0)s.savings*=1+Math.max(y.savingsInterestFloor,s.economy.interest*y.savingsInterestMultiplier);if(s.investments>0){const before=s.investments,marketReturn=rand(...(s.economy.marketIndex>1?y.investmentReturnAboveOne:y.investmentReturnBelowOne));s.investments=Math.max(0,s.investments*(1+marketReturn));s.lastInvestmentChange=Math.round(s.investments-before);s.lastInvestmentRate=marketReturn;log(`My investments ${s.lastInvestmentChange>=0?'gained':'lost'} ${money(Math.abs(s.lastInvestmentChange))} this year (${marketReturn>=0?'+':''}${(marketReturn*100).toFixed(1)}%).`)}else{s.lastInvestmentChange=0;s.lastInvestmentRate=null}for(const i of s.inventory){i.condition=clamp(i.condition-(i.conditionLoss||6)+rand(...y.inventoryConditionDrift));i.value=Math.max(50,i.value*(1-rand(...y.inventoryDepreciation)));if(i.type==='Vehicle'&&i.condition<y.vehicleBreakdownCondition&&Math.random()<y.vehicleBreakdownChance){const repair=Math.round(rand(...y.vehicleRepair)),paid=Math.min(s.cash,repair);s.cash-=paid;s.debt+=repair-paid;i.condition=clamp(i.condition+y.vehicleRepairConditionGain);log(`Age ${s.age}: ${i.name} broke down. Repairs cost ${money(repair)}.`)}}if(s.cash<0){const shortfall=Math.round(Math.abs(s.cash));s.lastDebtShortfall=shortfall;s.debt+=shortfall;s.cash=0;if(s.credit!==null)s.credit=Math.max(300,s.credit-y.negativeCashCreditPenalty);log(`I couldn't cover ${money(shortfall)} of my annual expenses, so it was added to my debt.`)}}
function npcYear(){const everyone=[...s.family.parents,...s.family.siblings,...s.family.children,...s.friends];if(s.partner)everyone.push(s.partner);for(const p of everyone){if(!p||!p.alive)continue;p.age++;p.quality=clamp(p.quality+rand(-3,2));if(!p.career&&p.age>=18&&Math.random()<.55)p.career=rn(Object.values(D.jobs)).name;if(p.age>=18)p.wealth=Math.max(0,(p.wealth||0)+rand(-2000,9000));if(p.age>70&&Math.random()<Math.min(.22,(p.age-69)/180)){p.alive=false;log(`Age ${s.age}: ${p.name}, your ${p.relation.toLowerCase()}, died at age ${p.age}.`);stat('happiness',-10);stat('stress',8)}}}
function relationshipYear(){if(!s.partner)return;const y=D.balance.yearly.relationships;s.partner.quality=clamp(s.partner.quality+rand(...y.partnerQualityDrift));if(s.partner.quality<y.breakupQualityThreshold&&Math.random()<y.breakupChance){log(`Age ${s.age}: Your relationship with ${s.partner.name} ended.`);s.relationship='Single';s.partner=null;stat('happiness',y.breakupHappiness)}}
function healthYear(){s.medicalCost=0;s.conditions=s.conditions.map(c=>({...c,duration:c.duration-1})).filter(c=>c.duration>0);for(const [id,ill] of Object.entries(D.illnesses)){if(s.age<ill.minAge||s.conditions.some(c=>c.id===id))continue;let chance=ill.chance*diff().health*(1+(100-s.health)/100)*(1+s.stress/160);if(Math.random()<chance){s.conditions.push({id,name:ill.name,duration:ill.duration});s.medicalCost+=ill.cost;stat('health',ill.health);log(`Age ${s.age}: You developed ${ill.name}. Medical costs were ${money(ill.cost)}.`)}}if(s.stress>70){stat('health',-4);stat('happiness',-3)}if(s.fitness<30)stat('health',-2);if(s.age>50)stat('health',-rand(.8,2.8));if(s.conditions.length)stat('health',-s.conditions.length)}
function businessYear(){if(!s.business)return;const ind=D.industries[s.business.industry];const econ=s.economy.state==='Boom'?1.16:s.economy.state==='Recession'?.82:1;const revenue=ind.baseRevenue*(1+s.business.level*.45)*(1+s.business.employees*.18)*econ*rand(.78,1.25);const payroll=s.business.employees*32000;const other=revenue*(1-ind.margin);const profit=revenue-payroll-other;s.business.revenue=Math.round(revenue);s.business.cash=Math.max(0,s.business.cash+profit);s.business.reputation=clamp(s.business.reputation+rand(-3,4));log(`Age ${s.age}: ${s.business.name} ${profit>=0?'earned':'lost'} ${money(Math.abs(profit))}.`);if(s.business.cash<=0&&profit<0&&Math.random()<.35){log(`Age ${s.age}: ${s.business.name} closed after running out of cash.`);s.business=null;stat('happiness',-10)}}
function processConsequences(){const due=s.pendingConsequences.filter(x=>x.age<=s.age);s.pendingConsequences=s.pendingConsequences.filter(x=>x.age>s.age);for(const c of due){applyEffects(c.effect||{});log(`Age ${s.age}: ${c.text}`)}}
function maybeDeath(){if(s.age<45&&s.health>10)return false;let chance=Math.max(0,(s.age-55)/700)+(100-s.health)/1200+(s.age>85?(s.age-85)/110:0)-(s.hidden.longevity-50)/2500;chance=Math.max(.001,chance);if(Math.random()<chance){s.dead=true;s.deathCause=s.health<25?'health complications':'natural causes';log(`Age ${s.age}: ${s.name} died from ${s.deathCause}.`);showDeath();return true}return false}
function ageYear(){if(s.dead)return;if(eventQueue.length)return showEvent();applyNeglect();s.age++;s.actionPoints=AP_MAX;s.actionUse={};ambientYear();processConsequences();economyYear();schoolYear();educationYear();npcYear();healthYear();careerYear();financeYear();businessYear();relationshipYear();if(maybeDeath()){commit();openPanel('life');return}queueEvent();commit();openPanel('life');showEvent()}

function conditionPass(c){switch(c){case'goodStudent':return(s.gpa||0)>=3.1;case'employed':return!!s.job;case'recession':return s.economy.state==='Recession'&&!!s.job;case'hasFamily':return s.family.parents.some(p=>p.alive)||s.family.siblings.some(p=>p.alive);case'hasChild':return s.family.children.some(p=>p.alive);case'hasBusiness':return!!s.business;case'hasPartner':return!!s.partner;default:return true}}
function queueEvent(){const chance={low:.35,normal:.58,high:.82}[s.settings.eventFrequency]||.58;if(Math.random()>chance)return;const valid=D.events.filter(e=>s.age>=e.minAge&&s.age<=e.maxAge&&meetsRequirements(e.requirements||[])&&conditionPass(e.condition));if(!valid.length)return;const weighted=[];valid.forEach(e=>{for(let i=0;i<(e.weight||1);i++)weighted.push(e)});eventQueue.push(rn(weighted))}
function showEvent(){if(!eventQueue.length)return;$('eventOverlay').classList.remove('hidden');const e=eventQueue[0];$('eventTitle').textContent=e.title;$('eventText').textContent=e.text;$('eventChoices').innerHTML='';e.choices.forEach(c=>{const b=document.createElement('button');b.textContent=c.label;b.onclick=()=>chooseEvent(c,e);$('eventChoices').appendChild(b)})}
function applyEffects(e,options={}){const scaledKeys=new Set(options.scaledKeys||[]),key=options.actionKey;for(const[k,v]of Object.entries(e||{})){const value=key&&scaledKeys.has(k)?scaled(v,key):v;if(k==='salaryPct'){s.salary=Math.round(s.salary*(1+value));continue}if(k==='businessCash'&&s.business){s.business.cash=Math.max(0,s.business.cash+value);continue}if(k==='businessRep'&&s.business){s.business.reputation=clamp(s.business.reputation+value);continue}if(k==='bossQuality'){s.bossQuality=clamp((s.bossQuality??50)+value);continue}if(k==='partnerQuality'&&s.partner){s.partner.quality=clamp(s.partner.quality+value);continue}stat(k,value)}}
function runDefinedAction(def,options={}){if(!def)return false;const miss=missingRequirements(def.requirements||[]);if(miss.length){if(options.messageId)msg(options.messageId,`Locked: ${miss.join(' • ')}.`);else toast(`Locked: ${miss.join(' • ')}`);return false}const key=def.actionKey||def.id;if(def.ap&&!actionCost(key,def.ap))return false;applyEffects(def.effects||{},{actionKey:key,scaledKeys:def.scaled||[]});if(def.bossQuality!==undefined){const gain=def.bossQualityScaled?scaled(def.bossQuality,key):def.bossQuality;s.bossQuality=clamp((s.bossQuality??50)+gain)}if(def.narrative)log(def.narrative);if(def.toast)toast(def.toast);if(def.ap&&(s.actionUse[key]||0)>1&&!def.toast)toast('Repeated action: reduced benefit');return true}
function chooseEvent(c,e){if(c.cost&&s.cash<c.cost){toast(`Need ${money(c.cost)}.`);return}if(c.cost)s.cash-=c.cost;let outcome=c.effect||{};if(c.chance){let p=.5;if(c.chance==='scholarship')p=.35+(s.gpa||0)/8+s.intelligence/500+s.hidden.luck/700;if(c.chance==='jobOffer')p=.45+s.social/350+s.performance/500;if(c.chance==='businessDeal')p=.42+s.skills.business/250+(s.business?.reputation||0)/500+s.hidden.luck/900;outcome=Math.random()<p?(c.success||{}):(c.failure||{})}applyEffects(outcome);if(c.familyQuality)[...s.family.parents,...s.family.siblings].filter(x=>x.alive).forEach(x=>x.quality=clamp(x.quality+c.familyQuality));if(c.partnerQuality&&s.partner)s.partner.quality=clamp(s.partner.quality+c.partnerQuality);if(c.childBoost){const child=s.family.children.filter(x=>x.alive)[0];if(child){child.skill=clamp((child.skill||50)+c.childBoost);child.quality=clamp(child.quality+4)}}if(c.spawnFriend)makeFriend(true);if(c.delayed)s.pendingConsequences.push({age:s.age+c.delayed.years,text:c.delayed.text,effect:c.delayed.effect});log(`Age ${s.age}: ${e.title} — ${c.result}`);eventQueue.shift();$('eventOverlay').classList.add('hidden');commit();showEvent()}
function showDeath(){const summary=`<p><strong>${escapeHtml(s.name)}</strong> lived to age <strong>${s.age}</strong>.</p><div class="kv">${lifetimeStatsHtml()}</div><p>Cause: ${escapeHtml(s.deathCause||'Unknown')}</p>`;$('deathSummary').innerHTML=summary;$('legacyChoices').innerHTML='';const adults=s.family.children.filter(c=>c.alive&&c.age>=18);for(const child of adults){const b=document.createElement('button');b.textContent=`Continue as ${child.name}, age ${child.age}`;b.onclick=()=>continueGeneration(child);$('legacyChoices').appendChild(b)}$('deathOverlay').classList.remove('hidden')}
function continueGeneration(child){const inherited=Math.max(0,netWorth()*.55);const ns=freshState(child.name,s.gender,s.birthplace,s.background,s.difficulty);ns.age=child.age;ns.location=s.location;ns.generation=s.generation+1;ns.cash=inherited;ns.education=child.age>=22?'College':child.age>=18?'High School':'None';ns.intelligence=clamp(child.skill||50);ns.social=clamp(child.quality||55);ns.family.parents=[npc(s.name,'Parent',s.age,80)];ns.family.parents[0].alive=false;ns.achievements=[...s.achievements,'legacy'];ns.history=[`Generation ${ns.generation}: ${child.name} inherited ${money(inherited)} and continued the family legacy.`];s=ns;eventQueue=[];$('deathOverlay').classList.add('hidden');commit();toast('Legacy continued')}

function educationCost(name){
  const p=D.education[name];if(!p)return null;
  const uni=p.usesUniversity?(D.universities[$('universitySelect').value]||D.universities['State University']):{tuition:1};
  const annual=Math.round(p.cost*uni.tuition),firstYear=Math.max(0,annual-(s.scholarship||0));
  return {annual,years:p.years,total:Math.max(0,annual*p.years-(s.scholarship||0)),firstYear};
}
function renderEducationCostPreview(){
  const choices=['Trade School','College','Graduate School'];
  $('educationCostPreview').innerHTML=choices.map(name=>{const c=educationCost(name);const finance=c.firstYear>s.cash?'Student loans may be required':'Current cash can cover the first year';return `<div class="education-cost-row"><strong>${escapeHtml(name)}</strong><span>${money(c.annual)}/year • ${c.years} years • Est. ${money(c.total)}</span><small>${s.scholarship?`Scholarship applied: ${money(s.scholarship)} • `:''}${finance}</small></div>`}).join('');
}
function startProgram(name){const p=D.education[name];if(!p)return;const miss=missingRequirements(p.requirements||[]);if(miss.length)return msg('educationMessage',`Locked: ${miss.join(' • ')}.`);if(p.usesUniversity){const u=$('universitySelect').value,req=D.universities[u]?.admission||0;if((s.gpa||2.5)<req)return msg('educationMessage',`${u} requires about a ${req.toFixed(1)} GPA.`);s.university=u}s.program=name;s.programYears=0;s.programNeed=p.years;s.programAnnualCost=p.cost;s.major=p.usesUniversity?$('majorSelect').value:'None';log(`Age ${s.age}: Started ${name}${s.major!=='None'?` in ${s.major}`:''}.`);commit()}
function jobOK(j){return meetsRequirements(j.requirements||[])}
function makeFriend(silent=false){if(s.friends.length>=12)return silent?null:msg('choiceMessage','You already have a large close-friend circle.');const f=npc(rn(D.names.adults),'Friend',Math.max(5,s.age+Math.floor(rand(-3,4))),Math.floor(rand(50,76)));s.friends.push(f);stat('social',3);stat('happiness',2);if(!silent)log(`Age ${s.age}: You became friends with ${f.name}.`);commit();return f}
function riskyConfirm(text){return !s.settings.confirmRisk||confirm(text)}

function makeDataButton(def,handler){const b=document.createElement('button');b.type='button';b.textContent=def.label||def.name||def.id;b.dataset.ap=String(def.ap||1);b.dataset.contentId=def.id||'';b.onclick=handler;return b}
function effectValue(key){return key in s.skills?s.skills[key]:s[key]}
function effectLabel(key){return key==='intelligence'?'Smarts':key[0].toUpperCase()+key.slice(1)}
function actionProgressText(def,before){
  const parts=[];
  for(const key of Object.keys(def.effects||{})){
    const old=before[key],now=effectValue(key);
    if(!Number.isFinite(old)||!Number.isFinite(now))continue;
    const delta=Math.round(now-old);
    if(delta===0)continue;
    parts.push(`${effectLabel(key)} ${Math.round(old)} → ${Math.round(now)} (${delta>0?'+':''}${delta})`);
  }
  return parts.join(' • ')||'No visible change — this stat may already be at its limit.';
}
function bindDataDrivenContent(){
  const mind=$('mindBodyActions'),skills=$('skillActions'),clubs=$('schoolClubActions');
  if(mind)mind.innerHTML='';if(skills)skills.innerHTML='';if(clubs)clubs.innerHTML='';
  Object.values(D.activities||{}).forEach(a=>{const host=a.group==='skills'?skills:mind;if(!host)return;host.appendChild(makeDataButton(a,()=>{const def={...a,scaled:Object.keys(a.effects||{}).filter(k=>(a.effects[k]||0)>0)},before={};Object.keys(a.effects||{}).forEach(k=>before[k]=effectValue(k));if(!runDefinedAction(def))return;const feedback=actionProgressText(def,before);commit();msg(a.group==='skills'?'skillMessage':'choiceMessage',feedback)}))});
  Object.values(D.schoolClubs||{}).forEach(c=>{if(!clubs)return;clubs.appendChild(makeDataButton(c,()=>{if(s.age<5||s.age>=18)return toast('School clubs are available while you are in school.');if(!runDefinedAction(c))return;s.club=c.name;commit()}))});
  const lawyer=$('lawyerSelect');if(lawyer){lawyer.innerHTML='';Object.entries(D.legalDefense||{}).forEach(([id,x])=>lawyer.add(new Option(`${x.name}${x.cost?` (${money(x.cost)})`:''}`,id)))}
}


const scrollLifeStoryNewest=()=>requestAnimationFrame(()=>{const el=$('log');if(el)el.scrollTop=0});
function openPanel(name){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$$('.panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='life')scrollLifeStoryNewest()}

function bind(){
  $$('.tab').forEach(b=>b.onclick=()=>openPanel(b.dataset.tab));
  $('homeBtn').onclick=()=>openPanel('life');$('settingsBtn').onclick=()=>openPanel('stats');$$('.menu-close').forEach(b=>b.onclick=()=>openPanel('life'));
  $('jobSelect').onchange=showJobRequirements;bindDataDrivenContent();D.genders.forEach(x=>$('genderInput').add(new Option(x,x)));Object.keys(D.locations).forEach(x=>{$('birthplaceInput').add(new Option(x,x));$('moveSelect').add(new Option(x,x))});Object.keys(D.backgrounds).forEach(x=>$('backgroundInput').add(new Option(x,x)));Object.keys(D.difficulties).forEach(x=>$('difficultyInput').add(new Option(x,x)));Object.keys(D.majors).forEach(x=>$('majorSelect').add(new Option(x,x)));Object.keys(D.universities).forEach(x=>$('universitySelect').add(new Option(x,x)));Object.keys(D.certifications).forEach(x=>$('certSelect').add(new Option(x,x)));Object.entries(D.housing).forEach(([k,h])=>$('housingSelect').add(new Option(h.name,k)));Object.entries(D.inventoryCatalog).forEach(([k,i])=>$('itemSelect').add(new Option(`${i.name} — ${money(i.price)}`,k)));Object.keys(D.industries).forEach(x=>$('industrySelect').add(new Option(x,x)));Object.entries(D.crimes).forEach(([k,c])=>$('crimeSelect').add(new Option(c.name,k)));
  $('newLifeBtn').onclick=()=>{if(!riskyConfirm('Start a new life and replace the current autosave?'))return;s=freshState($('nameInput').value.trim()||'Player',$('genderInput').value,$('birthplaceInput').value,$('backgroundInput').value,$('difficultyInput').value);eventQueue=[];$('deathOverlay').classList.add('hidden');msg('characterMessage','New life started.');commit()};$('ageBtn').onclick=ageYear;
  $('studySchoolBtn').onclick=()=>{if(s.age<5||s.age>=18)return;if(!actionCost('schoolStudy'))return;const m=actionMultiplier('schoolStudy');s.gpa=Math.min(4,(s.gpa??2.5)+.18*m);stat('intelligence',scaled(2,'schoolStudy'));stat('stress',3);log('I studied harder for school.');msg('schoolMessage',m<1?'GPA improved, but repeated studying had diminishing returns.':'GPA improved.');commit()};

  $('datingPreferenceSelect').onchange=()=>{s.datingPreference=$('datingPreferenceSelect').value;commit()};$('universitySelect').onchange=()=>{renderEducationCostPreview()};
  $('tradeBtn').onclick=()=>startProgram('Trade School');$('collegeBtn').onclick=()=>startProgram('College');$('gradBtn').onclick=()=>startProgram('Graduate School');$('dropoutBtn').onclick=()=>{if(!s.program)return msg('educationMessage','You are not enrolled.');log(`Age ${s.age}: Dropped out of ${s.program}.`);s.program=null;s.programYears=0;s.programNeed=0;s.programAnnualCost=0;stat('stress',-4);commit()};
  $('certBtn').onclick=()=>{const name=$('certSelect').value,c=D.certifications[name];if(s.certifications.includes(name))return msg('certMessage','Already earned.');const miss=missingRequirements(c.requirements||[]);if(miss.length)return msg('certMessage',`Locked: ${miss.join(' • ')}.`);if(s.cash<c.cost){s.debt+=c.cost}else s.cash-=c.cost;s.certifications.push(name);Object.entries(c.boost||{}).forEach(([k,v])=>stat(k,v));log(`Age ${s.age}: Earned ${name}.`);msg('certMessage','Certification earned.');commit()};
  $('applyBtn').onclick=()=>{const k=$('jobSelect').value,j=D.jobs[k],a=D.balance.career.apply;if(!jobOK(j))return msg('careerMessage',`Locked: ${jobMissing(j).join(' • ')}.`);if(!actionCost(a.actionKey,a.ap))return;const chance=a.baseChance+s.social/a.socialDivisor+s.intelligence/a.intelligenceDivisor+(j.skill?s.skills[j.skill]/a.jobSkillDivisor:0)+s.certifications.length*a.certBonusEach-(s.criminalRecord?a.criminalPenalty:0)+s.hidden.luck/a.luckDivisor;if(Math.random()>chance)return msg('careerMessage','Interview unsuccessful. Improve your qualifications and try again.');s.job=k;s.salary=jobSalary(j);s.performance=a.startPerformance;s.jobYears=0;s.company=rn(D.companies);s.bossQuality=Math.round(rand(...a.bossQuality));s.jobsHeld++;log(`Age ${s.age}: Hired as ${j.name} at ${s.company}.`);msg('careerMessage','You got the job!');commit()};
  $('workBtn').onclick=()=>{if(runDefinedAction(D.balance.career.work))commit()};$('networkBtn').onclick=()=>{if(runDefinedAction(D.balance.career.network))commit()};
  $('promotionBtn').onclick=()=>{if(!s.job)return;const a=D.balance.career.promotion;if(!actionCost(a.actionKey,a.ap))return;const j=D.jobs[s.job],next=j.next&&D.jobs[j.next];if(next&&jobOK(next)&&s.performance>=a.minPerformance&&s.bossQuality>=a.minBossQuality){s.job=j.next;s.salary=jobSalary(next);s.performance=a.promotionPerformance;s.jobYears=0;log(`Age ${s.age}: Promoted to ${next.name}.`);msg('careerMessage',`Promoted to ${next.name}!`)}else if(Math.random()<a.raiseBaseChance+s.performance/a.performanceDivisor+s.social/a.socialDivisor+(s.bossQuality||0)/a.bossDivisor){s.salary=Math.round(s.salary*rand(...a.raiseRange));log(`I received a raise to ${money(s.salary)} per year.`);msg('careerMessage',`Raise approved. New salary ${money(s.salary)}.`)}else msg('careerMessage','Promotion denied.');commit()};$('quitBtn').onclick=()=>{if(!s.job)return;log(`Age ${s.age}: You quit your job at ${s.company}.`);s.job=null;s.salary=0;s.performance=0;s.company=null;s.bossQuality=null;commit()};
  $('saveMoneyBtn').onclick=()=>{const f=F.save,a=f.amount,miss=missingRequirements(f.requirements||[]);if(miss.length)return msg('financeMessage',`Locked: ${miss.join(' • ')}.`);s.cash-=a;s.savings+=a;commit()};$('withdrawSavingsBtn').onclick=()=>{const a=Math.min(F.withdraw.amount,s.savings);s.savings-=a;s.cash+=a;commit()};$('loanBtn').onclick=()=>{const f=F.loan,miss=missingRequirements(f.requirements||[]);if(miss.length)return msg('financeMessage',`Loan denied: ${miss.join(' • ')}.`);s.cash+=f.amount;s.debt+=f.amount;s.credit-=f.creditPenalty;commit()};const payDebt=amount=>{const f=F.debtPayment,p=Math.min(Math.max(0,Math.round(amount)),Math.round(s.cash),Math.round(s.debt));if(p<=0)return msg('financeMessage',s.debt<=0?'You have no debt to pay.':'You need cash to make a debt payment.');s.cash-=p;s.debt=Math.max(0,s.debt-p);if(s.credit!==null)s.credit=Math.min(850,s.credit+f.creditGain);log(`I paid ${money(p)} toward my debt.`);commit();msg('financeMessage',`${money(p)} paid toward debt.`)};
  $('payDebtBtn').onclick=()=>payDebt(F.debtPayment.options?.[0]||F.debtPayment.amount);
  $('payDebt10000Btn').onclick=()=>payDebt(F.debtPayment.options?.[1]||10000);
  $('payDebt25Btn').onclick=()=>payDebt(s.debt*(F.debtPayment.percentOption||.25));
  $('payDebtAllBtn').onclick=()=>payDebt(s.debt);$('investBtn').onclick=()=>{const f=F.invest,a=f.amount,miss=missingRequirements(f.requirements||[]);if(miss.length)return msg('investmentMessage',`Locked: ${miss.join(' • ')}.`);s.cash-=a;s.investments+=a;log(`I invested ${money(a)}.`);msg('investmentMessage',`${money(a)} moved from Cash to Investments.`);commit()};
  const sellInvestments=amount=>{const a=Math.min(Math.max(0,Math.round(amount)),Math.round(s.investments));if(a<=0)return msg('investmentMessage','No investments available to sell.');s.investments=Math.max(0,s.investments-a);s.cash+=a;log(`I sold ${money(a)} of my investments.`);commit();msg('investmentMessage',`${money(a)} moved from Investments to Cash.`)};
  $('sellInvest1000Btn').onclick=()=>sellInvestments(1000);
  $('sellInvest25Btn').onclick=()=>sellInvestments(s.investments*.25);
  $('sellInvestAllBtn').onclick=()=>sellInvestments(s.investments);$('bankruptcyBtn').onclick=()=>{const f=F.bankruptcy;if(!riskyConfirm('Declare bankruptcy? This clears debt but destroys credit and investments.'))return;s.debt=0;s.credit=f.credit;s.investments=0;stat('happiness',f.happiness);stat('stress',f.stress);log(`Age ${s.age}: Declared bankruptcy.`);commit()};
  $('housingBtn').onclick=()=>{const key=$('housingSelect').value,h=D.housing[key];if(s.age<h.minAge)return msg('housingMessage','Too young for that housing option.');if(key==='parents'){s.housing='parents';commit();return}if(!h.owned){s.housing=key;log(`Age ${s.age}: Moved into an apartment.`);commit();return}const price=h.price*location().housing*s.economy.housingIndex,down=price*.1;if((s.credit||0)<620)return msg('housingMessage','Credit 620+ required.');if(s.cash<down)return msg('housingMessage',`Need ${money(down)} down.`);s.cash-=down;s.debt+=price-down;s.housing=key;s.credit-=12;s.stats.homesOwned++;log(`Age ${s.age}: Bought a ${h.name} for ${money(price)}.`);commit()};
  $('maintainItemsBtn').onclick=()=>{if(!s.inventory.length)return msg('inventoryMessage','You do not own anything to maintain.');if(s.cash<500)return msg('inventoryMessage','Need $500.');s.cash-=500;s.inventory.forEach(i=>i.condition=clamp(i.condition+18));msg('inventoryMessage','Owned items maintained.');commit()};$('buyItemBtn').onclick=()=>{const key=$('itemSelect').value,it=D.inventoryCatalog[key];if(s.cash<it.price)return msg('inventoryMessage',`Need ${money(it.price)}.`);s.cash-=it.price;s.inventory.push({id:uid(),key,name:it.name,type:it.type,condition:100,value:Math.round(it.price*.82),conditionLoss:it.conditionLoss});log(`Age ${s.age}: Bought ${it.name}.`);commit()};
  $('startBusinessBtn').onclick=()=>{if(!canAdult())return msg('businessMessage','You must be an adult and not incarcerated.');if(s.business)return msg('businessMessage','You already own a business.');const industry=$('industrySelect').value,ind=D.industries[industry];if(s.cash<ind.start)return msg('businessMessage',`Need ${money(ind.start)}.`);s.cash-=ind.start;s.business={name:`${s.name}'s ${industry}`,industry,level:1,employees:0,reputation:50,cash:ind.start*.3,revenue:0};s.stats.businessesStarted++;stat('business',8);log(`Age ${s.age}: Started ${s.business.name}.`);commit()};$('hireBtn').onclick=()=>{if(!s.business)return;if(s.business.cash<5000)return msg('businessMessage','Business needs $5,000 cash to hire.');s.business.cash-=5000;s.business.employees++;s.business.reputation=clamp(s.business.reputation+2);commit()};$('upgradeBusinessBtn').onclick=()=>{if(!s.business)return;if(s.cash<10000)return msg('businessMessage','Need $10,000 personal cash.');s.cash-=10000;s.business.cash+=10000;s.business.level++;stat('business',4);commit()};$('businessBankruptcyBtn').onclick=()=>{if(!s.business)return;if(!riskyConfirm('Close the business through bankruptcy? Its cash and value will be lost.'))return;log(`Age ${s.age}: ${s.business.name} entered bankruptcy.`);s.business=null;stat('happiness',-8);stat('stress',10);commit()};$('sellBusinessBtn').onclick=()=>{if(!s.business)return;const v=businessValue();if(!riskyConfirm(`Sell the business for about ${money(v)}?`))return;s.cash+=v;log(`Age ${s.age}: Sold ${s.business.name} for ${money(v)}.`);s.business=null;commit()};
  $('dateBtn').onclick=()=>{const r=R.date,miss=missingRequirements(r.requirements||[]);if(miss.length)return msg('relationshipMessage',`Locked: ${miss.join(' • ')}.`);if(!actionCost('dating',r.ap))return;const chance=(s.looks+s.social+s.happiness)/330+s.hidden.luck/1000;if(Math.random()<chance){const minPartnerAge=s.age>=18?18:r.minAge,pref=s.datingPreference||'Anyone',gender=pref==='Women'?'Female':pref==='Men'?'Male':(Math.random()<.5?'Female':'Male'),pool=gender==='Female'?(D.names.female||D.names.adults):(D.names.male||D.names.adults);s.partner=npc(rn(pool),'Partner',Math.max(minPartnerAge,s.age+Math.floor(rand(-3,4))),r.startQuality,gender);s.relationship='Dating';stat('happiness',r.happiness);log(`Age ${s.age}: Started dating ${s.partner.name}.`);msg('relationshipMessage',`You started dating ${s.partner.name}.`)}else msg('relationshipMessage','No luck this time.');commit()};
  $('partnerTimeBtn').onclick=()=>{if(!s.partner)return;const r=R.partnerTime;if(!actionCost('partnerTime',r.ap))return;s.partner.quality=clamp(s.partner.quality+scaled(r.quality,'partnerTime'));stat('happiness',scaled(r.happiness,'partnerTime'));stat('stress',r.stress);log(`I went on a date with ${s.partner.name}.`);commit()};
  $('giftBtn').onclick=()=>{if(!s.partner)return;const r=R.gift;if(s.cash<r.cost)return msg('relationshipMessage',`Need ${money(r.cost)}.`);if(!actionCost('partnerTime',r.ap))return;s.cash-=r.cost;s.partner.quality=clamp(s.partner.quality+r.quality);log(`I bought ${s.partner.name} a gift.`);commit()};
  $('argueBtn').onclick=()=>{if(!s.partner)return;const r=R.argue;if(!actionCost('partnerTime',r.ap))return;const good=Math.random()<r.baseSuccess+s.skills.communication/180;if(good){s.partner.quality=clamp(s.partner.quality+r.qualitySuccess);stat('stress',r.stressSuccess);log(`I talked through a problem with ${s.partner.name}.`);msg('relationshipMessage','You talked through the problem.')}else{s.partner.quality=clamp(s.partner.quality+r.qualityFail);stat('stress',r.stressFail);log(`I got into an argument with ${s.partner.name}.`);msg('relationshipMessage','The conversation turned into an argument.')}commit()};
  $('proposeBtn').onclick=()=>{if(!s.partner)return msg('relationshipMessage','You need a partner first.');const r=R.propose,miss=missingRequirements(r.requirements||[]);if(miss.length)return msg('relationshipMessage',`Locked: ${miss.join(' • ')}.`);const accepted=Math.random()<r.baseSuccess+s.partner.quality/220+s.social/500;if(accepted){s.relationship='Engaged';s.partner.relation='Fiancé';log(`Age ${s.age}: ${s.partner.name} accepted your proposal.`);msg('relationshipMessage','You are engaged!')}else{s.partner.quality=clamp(s.partner.quality+r.declineQuality);msg('relationshipMessage','The proposal was declined.')}commit()};
  $('marryBtn').onclick=()=>{if(!s.partner)return msg('relationshipMessage','You need a partner first.');const r=R.marry,miss=missingRequirements(r.requirements||[]);if(miss.length)return msg('relationshipMessage',`Locked: ${miss.join(' • ')}.`);s.relationship='Married';s.partner.relation='Spouse';stat('happiness',r.happiness);log(`Age ${s.age}: Married ${s.partner.name}.`);commit()};
  $('breakupBtn').onclick=()=>{if(!s.partner)return;const name=s.partner.name;log(`Age ${s.age}: ${s.relationship==='Married'?`Divorced ${name}`:`Ended the relationship with ${name}`}.`);if(s.relationship==='Married'&&s.family.children.some(c=>c.alive&&c.age<18)){s.custody='Shared';log(`Age ${s.age}: Shared custody was arranged for the children.`)}s.relationship='Single';s.partner=null;stat('happiness',R.breakup.happiness);commit()};
  $('childBtn').onclick=()=>{const r=R.child,miss=missingRequirements(r.requirements||[]);if(miss.length)return msg('relationshipMessage',`Locked: ${miss.join(' • ')}.`);if(!actionCost('childAttempt',r.ap))return;const chance=r.baseChance+s.hidden.fertility/180;if(Math.random()<chance){const c=npc(rn(D.names.children),'Child',0,82);c.skill=Math.round(rand(35,65));s.family.children.push(c);s.cash=Math.max(0,s.cash-r.birthCost);stat('happiness',r.happiness);stat('stress',r.stress);log(`Age ${s.age}: Child ${c.name} was born.`);msg('relationshipMessage',`You welcomed ${c.name}.`)}else msg('relationshipMessage','No child this year.');commit()};
  $('familyTimeBtn').onclick=()=>{const r=R.familyTime;if(!actionCost('familyTime',r.ap))return;const gain=scaled(r.quality,'familyTime');[...s.family.parents,...s.family.siblings,...s.family.children].filter(p=>p.alive).forEach(p=>p.quality=clamp(p.quality+gain));stat('happiness',scaled(r.happiness,'familyTime'));stat('stress',r.stress);log('I spent quality time with my family.');commit()};
  $('childSupportBtn').onclick=()=>{const r=R.childSupport,kids=s.family.children.filter(x=>x.alive&&x.age<18);if(!kids.length)return msg('childSupportMessage',`Locked: You don't have children to support.`);if(s.cash<r.cost)return msg('childSupportMessage',`Locked: Need ${money(r.cost)} cash.`);if((s.actionPoints??0)<r.ap)return msg('childSupportMessage',`Locked: Need ${r.ap} AP.`);if(!actionCost('familyTime',r.ap))return;s.cash-=r.cost;kids.forEach(k=>{k.quality=clamp(k.quality+r.quality);k.skill=clamp((k.skill||50)+r.skill)});s.stats.childrenRaised+=kids.length;log('I spent extra time and money supporting my children.');msg('childSupportMessage','You supported your children.');commit()};
  $('makeFriendBtn').onclick=()=>{if(!actionCost('socialize',R.makeFriend.ap))return;makeFriend()};

  $('crimeBtn').onclick=()=>{const key=$('crimeSelect').value,c=D.crimes[key];if(s.age<(c.minAge||18))return msg('crimeMessage',`You must be age ${c.minAge||18}+ for this action.`);if(s.jailYears>0)return msg('crimeMessage','You are currently incarcerated.');if(!riskyConfirm(`Attempt ${c.name}? You may be fined or jailed.`))return;if(!actionCost('crime',2))return;s.stats.crimes++;stat('karma',c.karma);const lawyer=D.legalDefense?.[$('lawyerSelect').value]||{cost:0,defense:0,jailReduction:0};let legalCost=lawyer.cost||0,defense=lawyer.defense||0,jailReduction=lawyer.jailReduction||0;if(legalCost){const lp=Math.min(s.cash,legalCost);s.cash-=lp;s.debt+=legalCost-lp}const caught=Math.random()<(c.caught*diff().crime+(50-s.karma)/450-(s.hidden.luck-50)/900-defense);if(caught){s.criminalRecord=true;const reducedFine=Math.round(c.fine*(1-defense*1.7));const shortage=Math.max(0,reducedFine-s.cash);s.cash=Math.max(0,s.cash-reducedFine);s.debt+=shortage;if(c.jail)s.jailYears=Math.max(0,c.jail-jailReduction);if(s.credit!==null)s.credit=Math.max(300,s.credit-20);stat('stress',12);log(`Age ${s.age}: Caught committing ${c.name}${c.jail?` and sentenced to ${c.jail} year(s)`:''}.`);msg('crimeMessage',`Caught. Court outcome: fine ${money(reducedFine)}${s.jailYears?` • Jail: ${s.jailYears} yrs`:' • No jail'}.`)}else{const gain=rand(c.gain[0],c.gain[1]);s.cash+=gain;log(`Age ${s.age}: Got away with ${c.name} and gained ${money(gain)}.`);msg('crimeMessage',`Got away with ${money(gain)}.`)}commit()};
  $('moveBtn').onclick=()=>{if(s.age<18)return msg('moveMessage','You must be 18+ to move on your own.');const city=$('moveSelect').value;if(city===s.location)return msg('moveMessage','You already live there.');if(s.cash<3000)return msg('moveMessage','Need $3,000 to move.');s.cash-=3000;s.location=city;s.stats.moves++;log(`Age ${s.age}: Moved to ${city}.`);commit()};
  $('saveSettingsBtn').onclick=()=>{s.settings.eventFrequency=$('eventFreqSelect').value;s.settings.confirmRisk=$('confirmRiskSelect').value==='yes';commit();toast('Settings saved')};$('saveSlotBtn').onclick=()=>saveSlot($('slotSelect').value);$('loadSlotBtn').onclick=()=>loadSlot($('slotSelect').value);$('deleteSlotBtn').onclick=()=>{const n=$('slotSelect').value;if(!riskyConfirm(`Delete Slot ${n}?`))return;localStorage.removeItem(slotKey(n));msg('slotMessage',`Deleted Slot ${n}.`)};
  $('manualSaveBtn').onclick=()=>saveAutosave(true);$('exportBtn').onclick=()=>{$('saveBox').value=JSON.stringify(s);msg('saveMessage','Save exported.');};$('importBtn').onclick=()=>{try{s=normalize(JSON.parse($('saveBox').value));msg('saveMessage','Save imported.');commit()}catch{msg('saveMessage','Invalid save data.')}};$('resetBtn').onclick=()=>{if(!riskyConfirm('Erase this life?'))return;s=freshState();eventQueue=[];commit()};$('restartAfterDeathBtn').onclick=()=>{s=freshState();eventQueue=[];$('deathOverlay').classList.add('hidden');commit()};
}

function init(){bind();if(!loadAutosave())s=freshState();$('nameInput').value=s.name;$('genderInput').value=s.gender;$('birthplaceInput').value=s.birthplace;$('backgroundInput').value=s.background;$('difficultyInput').value=s.difficulty;$('moveSelect').value=s.location;$('universitySelect').value=s.university||'State University';render();saveAutosave()}
init();
})();
