window.GAME_DATA={
backgrounds:{Balanced:{health:0,happiness:0,intelligence:0,looks:0,fitness:0,social:0,cash:0},Academic:{intelligence:8,social:-2,happiness:-2},Athletic:{fitness:8,health:5,intelligence:-2},Social:{social:8,happiness:4,intelligence:-2},Wealthy:{cash:5000,happiness:3,karma:-2},Struggling:{cash:0,stress:8,karma:4,intelligence:2}},
birthplaces:['Columbia, SC','Charlotte, NC','Atlanta, GA','New York, NY','Los Angeles, CA','Chicago, IL','Miami, FL','Houston, TX'],
eduRank:{'None':0,'High School':1,'Trade School':2,'College':3,'Graduate':4},
assets:{usedcar:{name:'Used Car',price:8000,value:6000,type:'cash',minAge:16,annual:1200},newcar:{name:'New Car',price:35000,value:28000,type:'finance',minAge:18,annual:2800},condo:{name:'Condo',price:120000,value:120000,type:'mortgage',minAge:18,annual:5000},house:{name:'House',price:280000,value:280000,type:'mortgage',minAge:18,annual:9000}},
names:{adults:['Alex','Jordan','Taylor','Morgan','Casey','Riley','Cameron','Avery','Parker','Drew','Jamie','Skyler'],children:['Noah','Liam','Mia','Emma','Lucas','Ava','Ethan','Sofia','Mason','Zoe','Leo','Maya']},
jobs:{
fastfood:{name:'Fast Food Worker',salary:22000,minAge:16,edu:'None',intel:0,social:0,skill:null,skillMin:0,next:'retail'},retail:{name:'Retail Associate',salary:28000,minAge:16,edu:'None',intel:0,social:35,skill:'communication',skillMin:20,next:'supervisor'},warehouse:{name:'Warehouse Technician',salary:39000,minAge:18,edu:'High School',intel:35,social:0,skill:'mechanical',skillMin:25,next:'industrialtech'},
supervisor:{name:'Retail Supervisor',salary:42000,minAge:19,edu:'High School',intel:35,social:50,skill:'communication',skillMin:40,next:'manager'},industrialtech:{name:'Industrial Technician',salary:56000,minAge:20,edu:'High School',intel:45,social:10,skill:'mechanical',skillMin:50,next:'electrician'},electrician:{name:'Electrician',salary:65000,minAge:18,edu:'Trade School',intel:45,social:0,skill:'mechanical',skillMin:55,next:'controls'},it:{name:'IT Support Specialist',salary:56000,minAge:18,edu:'High School',intel:55,social:35,skill:'technology',skillMin:45,next:'sysadmin'},sysadmin:{name:'Systems Administrator',salary:82000,minAge:20,edu:'College',intel:65,social:30,skill:'technology',skillMin:65,next:'networkeng'},networkeng:{name:'Network Engineer',salary:98000,minAge:22,edu:'College',intel:70,social:35,skill:'technology',skillMin:75,next:'itmanager'},itmanager:{name:'IT Manager',salary:125000,minAge:26,edu:'College',intel:65,social:70,skill:'communication',skillMin:65,next:null},controls:{name:'Controls Specialist',salary:90000,minAge:21,edu:'Trade School',intel:65,social:25,skill:'mechanical',skillMin:70,next:'automation'},automation:{name:'Automation Engineer',salary:105000,minAge:22,edu:'College',intel:72,social:25,skill:'technology',skillMin:70,next:'engineeringmanager'},engineeringmanager:{name:'Engineering Manager',salary:135000,minAge:28,edu:'College',intel:70,social:70,skill:'communication',skillMin:65,next:null},manager:{name:'Operations Manager',salary:105000,minAge:24,edu:'College',intel:60,social:70,skill:'business',skillMin:55,next:'director'},director:{name:'Operations Director',salary:145000,minAge:30,edu:'College',intel:68,social:75,skill:'business',skillMin:70,next:null},doctor:{name:'Physician',salary:215000,minAge:26,edu:'Graduate',intel:85,social:45,skill:'communication',skillMin:45,next:null}},
achievements:[{id:'adult',name:'Welcome to Adulthood',test:s=>s.age>=18},{id:'graduate',name:'Degree Earned',test:s=>['College','Graduate'].includes(s.education)},{id:'sixfig',name:'Six-Figure Career',test:s=>s.salary>=100000},{id:'millionaire',name:'Millionaire',test:s=>s.netWorth>=1000000},{id:'family',name:'Growing Family',test:s=>s.family.children.length>=2},{id:'business',name:'Entrepreneur',test:s=>s.businessLevel>=1},{id:'healthy',name:'Peak Condition',test:s=>s.health>=95&&s.fitness>=85}],
events:[
{id:'friend',minAge:5,maxAge:17,weight:5,title:'A New Friend',text:'A classmate wants to hang out after school.',choices:[{label:'Hang out',effect:{social:5,happiness:4,friends:1},result:'You made a new friend.'},{label:'Study instead',effect:{intelligence:4,stress:2},result:'You focused on school.'}]},
{id:'bully',minAge:7,maxAge:16,weight:3,title:'School Trouble',text:'Another student keeps bothering you.',choices:[{label:'Tell an adult',effect:{karma:3,stress:-3},result:'The situation improved.'},{label:'Stand up for yourself',effect:{fitness:2,stress:2},result:'You stood your ground.'},{label:'Ignore it',effect:{happiness:-4,stress:5},result:'It kept bothering you.'}]},
{id:'party',minAge:14,maxAge:20,weight:3,title:'Party Invitation',text:'You are invited to a big party.',choices:[{label:'Go',effect:{social:5,happiness:4,stress:-2},result:'You had a great time.'},{label:'Stay home',effect:{intelligence:3,stress:-1},result:'You had a quiet night.'}]},
{id:'workrecognition',minAge:18,maxAge:70,requiresJob:true,weight:4,title:'Recognition at Work',text:'Your supervisor praises your work.',choices:[{label:'Ask for responsibility',effect:{performance:8,stress:4},result:'You took on more responsibility.'},{label:'Enjoy it',effect:{happiness:4,stress:-2},result:'You enjoyed the recognition.'}]},
{id:'layoff',minAge:18,maxAge:70,requiresJob:true,weight:1,title:'Company Restructuring',text:'Your employer announces layoffs.',choices:[{label:'Volunteer for extra duties',effect:{performance:7,stress:6},result:'You made yourself harder to cut.'},{label:'Prepare a backup plan',effect:{technology:2,business:2,stress:2},result:'You prepared for uncertainty.'}]},
{id:'familyarg',minAge:6,maxAge:85,requiresFamily:true,weight:3,title:'Family Argument',text:'Tension flares at home.',choices:[{label:'Calm everyone down',effect:{communication:3,karma:2,familyQuality:4},result:'You helped settle things.'},{label:'Stay out of it',effect:{familyQuality:-2,stress:-1},result:'You avoided the conflict.'}]},
{id:'health',minAge:30,maxAge:95,weight:3,title:'Health Warning',text:'A checkup suggests you should take better care of yourself.',choices:[{label:'Get serious about health',effect:{health:6,fitness:4,stress:2},result:'You made healthier choices.'},{label:'Ignore it',effect:{health:-5,happiness:1},result:'You changed nothing.'}]},
{id:'wallet',minAge:8,maxAge:90,weight:2,title:'Found Wallet',text:'You find a wallet containing $100.',choices:[{label:'Return it',effect:{karma:8,happiness:2,cash:20},result:'The owner rewarded you.'},{label:'Keep it',effect:{karma:-10,cash:100,stress:2},result:'You kept the cash.'}]}
]};
