(()=>{'use strict';
const D=window.GAME_DATA,$=id=>document.getElementById(id),clamp=n=>Math.max(0,Math.min(100,Math.round(n))),money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Math.round(n));
const SAVE_KEY='lifeSimV05Save';let s=null,eventQueue=[];const uid=()=>globalThis.crypto&&typeof globalThis.crypto.randomUUID==='function'?globalThis.crypto.randomUUID():String(Date.now()+Math.random());
const person=(name,relation,age,quality=65)=>({id:uid(),name,relation,age,quality,alive:true});const rn=a=>a[Math.floor(Math.random()*a.length)];
function makeFamily(){return {parents:[person(rn(D.names.adults),'Parent',25+Math.floor(Math.random()*16),65),person(rn(D.names.adults),'Parent',25+Math.floor(Math.random()*18),65)],siblings:Math.random()<.55?[person(rn(D.names.children),'Sibling',Math.floor(Math.random()*7),60)]:[],children:[],quality:70};}
function freshState(name='Player',gender='Male',birthplace=D.birthplaces[0],background='Balanced'){let st={version:'0.5.0',name,gender,birthplace,background,age:0,cash:0,savings:0,health:100,happiness:70,intelligence:50,looks:50,fitness:50,social:50,stress:10,karma:50,skills:{technology:10,mechanical:10,business:10,communication:10,creativity:10},schoolLevel:'Not started',gpa:null,club:'None',education:'None',program:null,programYears:0,programNeed:0,job:null,salary:0,performance:0,jobYears:0,debt:0,credit:null,investments:0,assets:[],relationship:'Single',relationshipQuality:null,friends:0,businessLevel:0,businessIncome:0,criminalRecord:false,family:makeFamily(),achievements:[],history:[`Age 0: ${name} was born in ${birthplace}.`],dead:false,deathCause:null};Object.entries(D.backgrounds[background]||{}).forEach(([k,v])=>{if(k in st)st[k]+=v;});return st;}
function normalize(raw){const b=freshState(raw?.name||'Player',raw?.gender||'Male',raw?.birthplace||D.birthplaces[0],raw?.background||'Balanced');const m={...b,...raw,skills:{...b.skills,...(raw.skills||{})},family:{...b.family,...(raw.family||{})}};m.family.parents=Array.isArray(m.family.parents)?m.family.parents:b.family.parents;m.family.siblings=Array.isArray(m.family.siblings)?m.family.siblings:[];m.family.children=Array.isArray(m.family.children)?m.family.children:[];m.assets=Array.isArray(m.assets)?m.assets:[];m.history=Array.isArray(m.history)?m.history:[];m.achievements=Array.isArray(m.achievements)?m.achievements:[];return m;}
function save(show=false){try{localStorage.setItem(SAVE_KEY,JSON.stringify(s));$('autosaveStatus').textContent='Saved';if(show)$('saveMessage').textContent='Game saved.';}catch{$('autosaveStatus').textContent='Save unavailable';}}function load(){try{const r=localStorage.getItem(SAVE_KEY);if(!r)return false;s=normalize(JSON.parse(r));return true}catch{return false}}
const log=t=>{s.history.push(t);if(s.history.length>300)s.history=s.history.slice(-300)};function stat(k,d){if(k in s.skills){s.skills[k]=clamp(s.skills[k]+d);return}if(['cash','savings','debt','investments','salary','businessIncome','friends'].includes(k)){s[k]=Math.max(0,(s[k]||0)+d);return}s[k]=clamp((s[k]||0)+d)}
function stage(){if(s.age<2)return'Baby';if(s.age<5)return'Toddler';if(s.age<13)return'Child';if(s.age<18)return'Teenager';if(s.age<65)return'Adult';return'Senior'}function schoolStage(){if(s.age<5)return'Not started';if(s.age<11)return'Elementary School';if(s.age<14)return'Middle School';if(s.age<18)return'High School';return'Graduated'}
function annualExpenses(){if(s.age<18)return 0;let e=12000+4200+2400+1800; // food, housing baseline, utilities, misc
s.assets.forEach(k=>e+=(D.assets[k]?.annual||0));e+=s.family.children.filter(c=>c.alive&&c.age<18).length*4500;return e}
function netWorth(){return s.cash+s.savings+s.investments+s.assets.reduce((a,k)=>a+(D.assets[k]?.value||0),0)-s.debt}
const eduOK=r=>D.eduRank[s.education]>=D.eduRank[r];function jobOK(j){return s.age>=j.minAge&&eduOK(j.edu)&&s.intelligence>=j.intel&&s.social>=j.social&&(!j.skill||s.skills[j.skill]>=j.skillMin)}
function renderStats(){const core=[['Health','health'],['Happiness','happiness'],['Intelligence','intelligence'],['Looks','looks'],['Fitness','fitness'],['Social','social'],['Stress','stress'],['Karma','karma']];$('statsGrid').innerHTML=core.map(([n,k])=>`<div class="stat"><span>${n}</span><strong>${Math.round(s[k])}</strong></div>`).join('');$('skillsGrid').innerHTML=Object.entries(s.skills).map(([k,v])=>`<div class="stat"><span>${k[0].toUpperCase()+k.slice(1)}</span><strong>${Math.round(v)}</strong></div>`).join('')}
function renderPeople(list,id){const c=$(id);c.innerHTML='';if(!list.length){c.textContent='None.';return}list.forEach(p=>{const d=document.createElement('div');d.className='person';d.innerHTML=`<div>${p.name} • ${p.relation}${p.alive?'':' • Deceased'}</div><span>Age ${p.age} • Bond ${Math.round(p.quality)}</span>`;c.appendChild(d)})}
function renderJobs(){const sel=$('jobSelect'),prev=sel.value;sel.innerHTML='';Object.entries(D.jobs).forEach(([k,j])=>{const o=document.createElement('option');o.value=k;o.textContent=`${j.name} — ${money(j.salary)}${jobOK(j)?'':' 🔒'}`;sel.appendChild(o)});if(prev&&D.jobs[prev])sel.value=prev}
function checkAchievements(){const view={...s,netWorth:netWorth()};D.achievements.forEach(a=>{if(!s.achievements.includes(a.id)&&a.test(view)){s.achievements.push(a.id);log(`Age ${s.age}: Achievement unlocked — ${a.name}.`)}})}
function render(){checkAchievements();$('ageVal').textContent=s.age;$('stageVal').textContent=stage();$('cashVal').textContent=money(s.cash);$('worthVal').textContent=money(netWorth());renderStats();$('schoolVal').textContent=s.schoolLevel;$('gpaVal').textContent=s.gpa===null?'—':s.gpa.toFixed(2);$('clubVal').textContent=s.club;$('eduVal').textContent=s.program?`${s.program} in progress`:s.education;$('eduProgress').textContent=s.program?`${s.programYears} / ${s.programNeed} years`:'—';$('jobVal').textContent=s.job?D.jobs[s.job].name:'None';$('salaryVal').textContent=money(s.salary);$('performanceVal').textContent=Math.round(s.performance);$('cash2Val').textContent=money(s.cash);$('savingsVal').textContent=money(s.savings);$('debtVal').textContent=money(s.debt);$('creditVal').textContent=s.credit===null?'—':Math.round(s.credit);$('investVal').textContent=money(s.investments);$('expensesVal').textContent=money(annualExpenses());$('assetsVal').textContent=s.assets.length?s.assets.map(k=>D.assets[k]?.name||k).join(', '):'No major assets.';$('relationshipVal').textContent=s.relationship;$('relationshipQuality').textContent=s.relationshipQuality===null?'—':Math.round(s.relationshipQuality);$('friendsVal').textContent=s.friends;$('businessVal').textContent=s.businessLevel?`Level ${s.businessLevel} company`:'None';$('businessIncomeVal').textContent=money(s.businessIncome);renderPeople([...s.family.parents,...s.family.siblings],'familyList');renderPeople(s.family.children,'childrenList');$('achievementsVal').innerHTML=s.achievements.length?s.achievements.map(id=>`<span class="chip">${D.achievements.find(a=>a.id===id)?.name||id}</span>`).join(''):'<span class="muted">None yet.</span>';$('log').innerHTML=[...s.history].reverse().slice(0,140).map(t=>`<div>${t}</div>`).join('');renderJobs();
const schoolAge=s.age>=5&&s.age<18;$('studySchoolBtn').disabled=!schoolAge;$('joinTechBtn').disabled=!schoolAge;$('joinSportsBtn').disabled=!schoolAge;$('joinArtsBtn').disabled=!schoolAge;$('tradeBtn').disabled=s.age<18||!!s.program||D.eduRank[s.education]>=2;$('collegeBtn').disabled=s.age<18||!!s.program||D.eduRank[s.education]>=3;$('gradBtn').disabled=s.age<22||!!s.program||s.education!=='College';$('workBtn').disabled=!s.job;$('promotionBtn').disabled=!s.job;$('quitBtn').disabled=!s.job;$('loanBtn').disabled=s.age<18;$('investBtn').disabled=s.age<18;$('payDebtBtn').disabled=s.debt<=0;$('bankruptcyBtn').disabled=s.debt<10000;$('dateBtn').disabled=s.age<16||s.relationship!=='Single';$('partnerTimeBtn').disabled=s.relationship==='Single';$('marryBtn').disabled=s.relationship!=='Dating';$('breakupBtn').disabled=s.relationship==='Single';$('childBtn').disabled=s.relationship==='Single'||s.age<18||s.age>55;$('startBusinessBtn').disabled=s.age<18||s.businessLevel>0;$('upgradeBusinessBtn').disabled=s.businessLevel===0;$('crimeBtn').disabled=s.age<12;$('ageBtn').disabled=s.dead}
function commit(show=false){render();save(show)}
function applyEffects(e){Object.entries(e||{}).forEach(([k,v])=>{if(k==='familyQuality'){s.family.quality=clamp(s.family.quality+v);[...s.family.parents,...s.family.siblings].forEach(p=>p.quality=clamp(p.quality+v));return}if(k==='relationshipQuality'&&s.relationshipQuality!==null){s.relationshipQuality=clamp(s.relationshipQuality+v);return}stat(k,v)})}
const eligibleEvents=()=>D.events.filter(e=>s.age>=e.minAge&&s.age<=e.maxAge&&(!e.requiresJob||s.job)&&(!e.requiresFamily||[...s.family.parents,...s.family.siblings].some(p=>p.alive)));function queueEvent(){if(Math.random()>.68)return;const pool=eligibleEvents();if(pool.length)eventQueue.push(pool[Math.floor(Math.random()*pool.length)])}function showEvent(){if(!eventQueue.length)return;const e=eventQueue.shift();$('eventTitle').textContent=e.title;$('eventText').textContent=e.text;$('eventChoices').innerHTML='';e.choices.forEach(c=>{const b=document.createElement('button');b.innerHTML=`<strong>${c.label}</strong><small>${Object.entries(c.effect||{}).map(([k,v])=>`${v>0?'+':''}${v} ${k}`).join(' • ')}</small>`;b.onclick=()=>{applyEffects(c.effect);log(`Age ${s.age}: ${c.result}`);$('eventOverlay').classList.add('hidden');commit();setTimeout(showEvent,80)};$('eventChoices').appendChild(b)});$('eventOverlay').classList.remove('hidden')}
function ageFamily(){[...s.family.parents,...s.family.siblings,...s.family.children].forEach(p=>{if(!p.alive)return;p.age++;if(Math.random()<.15)p.quality=clamp(p.quality-1);if(p.age>70&&Math.random()<Math.min(.2,(p.age-70)*.008)){p.alive=false;log(`Age ${s.age}: ${p.name} (${p.relation}) passed away.`);stat('happiness',-10);stat('stress',8)}})}
function maybeDeath(){let chance=0;if(s.age>65)chance+=(s.age-65)*.003;if(s.health<35)chance+=(35-s.health)*.006;if(s.age>90)chance+=.08;if(Math.random()<chance||s.health<=0){s.dead=true;s.deathCause=s.health<=0?'poor health':'natural causes';$('deathSummary').innerHTML=`<p><strong>${s.name}</strong> died at age <strong>${s.age}</strong> from ${s.deathCause}.</p><p>Final net worth: <strong>${money(netWorth())}</strong></p><p>Career: <strong>${s.job?D.jobs[s.job].name:'None'}</strong></p><p>Education: <strong>${s.education}</strong></p><p>Children: <strong>${s.family.children.length}</strong> • Achievements: <strong>${s.achievements.length}</strong></p>`;$('deathOverlay').classList.remove('hidden');log(`Age ${s.age}: ${s.name} died from ${s.deathCause}.`);return true}return false}
function ageYear(){if(s.dead||!$('eventOverlay').classList.contains('hidden'))return;s.age++;ageFamily();s.schoolLevel=schoolStage();if(s.age===5){s.gpa=2.7;log('Age 5: You started elementary school.')}if(s.age>=5&&s.age<18){s.gpa=Math.max(0,Math.min(4,s.gpa+(s.intelligence-50)/700+(Math.random()-.5)*.18));if(s.gpa<1.5){stat('stress',4);stat('happiness',-2)}}if(s.age===11)log('Age 11: You started middle school.');if(s.age===14)log('Age 14: You started high school.');if(s.age===18){s.schoolLevel='Graduated';if(s.gpa>=1.8){s.education='High School';log(`Age 18: You graduated high school with a ${s.gpa.toFixed(2)} GPA.`)}else log('Age 18: You did not graduate high school.');if(s.credit===null)s.credit=650}
if(s.program){s.programYears++;stat('stress',4);stat('intelligence',3);if(s.programYears>=s.programNeed){s.education=s.program==='Graduate School'?'Graduate':s.program;log(`Age ${s.age}: Completed ${s.program}.`);s.program=null;s.programYears=0;s.programNeed=0}}
if(s.job){s.jobYears++;const gross=s.salary,net=gross*.82;s.cash+=net-annualExpenses();stat('performance',-2);stat('stress',3);if(Math.random()<.06){log(`Age ${s.age}: You were laid off.`);s.job=null;s.salary=0;s.performance=0;stat('stress',10)}else if(s.performance<20&&Math.random()<.25){log(`Age ${s.age}: You were fired for poor performance.`);s.job=null;s.salary=0;s.performance=0}}else if(s.age>=18){s.cash-=annualExpenses();stat('happiness',-3);stat('stress',4)}
if(s.businessLevel){const p=s.businessIncome*(.75+Math.random()*.65);s.cash+=p;log(`Age ${s.age}: Business profit ${money(p)}.`)}if(s.debt>0){s.debt*=1.075;if(s.credit!==null)s.credit=Math.max(300,s.credit-4)}if(s.savings>0)s.savings*=1.025;if(s.investments>0)s.investments*=1+((Math.random()*.26)-.08);if(s.stress>70){stat('health',-5);stat('happiness',-4)}if(s.fitness<30)stat('health',-2);if(s.age>50)stat('health',-(1+Math.random()*2.5));if(s.relationship!=='Single'&&s.relationshipQuality!==null){s.relationshipQuality=clamp(s.relationshipQuality-2);if(s.relationshipQuality<15&&Math.random()<.25){log(`Age ${s.age}: Your relationship ended.`);s.relationship='Single';s.relationshipQuality=null;stat('happiness',-15)}}if(maybeDeath()){commit();return}queueEvent();commit();showEvent()}
function program(name,cost,years){if(s.cash>=cost)s.cash-=cost;else s.debt+=cost;s.program=name;s.programYears=0;s.programNeed=years;log(`Age ${s.age}: Started ${name}.`);commit()}
function msg(id,text){$(id).textContent=text}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===b.dataset.tab))});
D.birthplaces.forEach(x=>$('birthplaceInput').add(new Option(x,x)));Object.keys(D.backgrounds).forEach(x=>$('backgroundInput').add(new Option(x,x)));$('newLifeBtn').onclick=()=>{s=freshState($('nameInput').value.trim()||'Player',$('genderInput').value,$('birthplaceInput').value,$('backgroundInput').value);eventQueue=[];$('deathOverlay').classList.add('hidden');msg('characterMessage','New life started.');commit()};$('ageBtn').onclick=ageYear;
$('studySchoolBtn').onclick=()=>{s.gpa=Math.min(4,(s.gpa??2.5)+.18);stat('intelligence',2);stat('stress',3);msg('schoolMessage','GPA improved.');commit()};$('joinTechBtn').onclick=()=>{s.club='Technology Club';stat('technology',5);stat('intelligence',2);commit()};$('joinSportsBtn').onclick=()=>{s.club='Sports Team';stat('fitness',6);stat('social',2);commit()};$('joinArtsBtn').onclick=()=>{s.club='Arts Club';stat('creativity',6);stat('happiness',2);commit()};$('tradeBtn').onclick=()=>program('Trade School',5000,2);$('collegeBtn').onclick=()=>program('College',12000,4);$('gradBtn').onclick=()=>program('Graduate School',25000,4);
$('applyBtn').onclick=()=>{const k=$('jobSelect').value,j=D.jobs[k];if(!jobOK(j))return msg('careerMessage',`Locked: age ${j.minAge}+, ${j.edu}, Intelligence ${j.intel}+, Social ${j.social}+${j.skill?`, ${j.skill} ${j.skillMin}+`:''}.`);const ch=.5+s.social/300+s.intelligence/450+(j.skill?s.skills[j.skill]/500:0)-(s.criminalRecord?.18:0);if(Math.random()>ch)return msg('careerMessage','Interview unsuccessful. Improve your qualifications and try again.');s.job=k;s.salary=j.salary;s.performance=50;s.jobYears=0;log(`Age ${s.age}: Hired as ${j.name}.`);msg('careerMessage','You got the job!');commit()};$('workBtn').onclick=()=>{stat('performance',8);stat('stress',5);msg('careerMessage','Performance +8, Stress +5.');commit()};$('promotionBtn').onclick=()=>{if(!s.job)return;const j=D.jobs[s.job],next=j.next&&D.jobs[j.next];if(next&&jobOK(next)&&s.performance>=65){s.job=j.next;s.salary=next.salary;s.performance=55;log(`Age ${s.age}: Promoted to ${next.name}.`);msg('careerMessage',`Promoted to ${next.name}!`)}else if(Math.random()<.15+s.performance/160+s.social/600){s.salary=Math.round(s.salary*1.08);msg('careerMessage',`Raise approved. New salary ${money(s.salary)}.`)}else msg('careerMessage','Promotion denied.');commit()};$('quitBtn').onclick=()=>{if(!s.job)return;log(`Age ${s.age}: You quit your job.`);s.job=null;s.salary=0;s.performance=0;commit()};
$('saveMoneyBtn').onclick=()=>{if(s.cash<500)return msg('financeMessage','Need $500 cash.');s.cash-=500;s.savings+=500;commit()};$('withdrawSavingsBtn').onclick=()=>{const a=Math.min(500,s.savings);s.savings-=a;s.cash+=a;commit()};$('loanBtn').onclick=()=>{if(s.credit<560)return msg('financeMessage','Loan denied. Credit too low.');s.cash+=5000;s.debt+=5000;s.credit-=12;msg('financeMessage','Borrowed $5,000.');commit()};$('payDebtBtn').onclick=()=>{const p=Math.min(1000,s.cash,s.debt);if(p<=0)return;s.cash-=p;s.debt-=p;if(s.credit!==null)s.credit=Math.min(850,s.credit+9);commit()};$('investBtn').onclick=()=>{if(s.cash<1000)return msg('financeMessage','Need $1,000 cash.');s.cash-=1000;s.investments+=1000;commit()};$('bankruptcyBtn').onclick=()=>{s.debt=0;s.credit=300;s.investments=0;stat('happiness',-12);stat('stress',12);log(`Age ${s.age}: Declared bankruptcy.`);msg('financeMessage','Debt cleared, but credit collapsed to 300.');commit()};
Object.entries(D.assets).forEach(([k,a])=>{const b=document.createElement('button');b.textContent=`Buy ${a.name} (${money(a.price)})`;b.onclick=()=>{if(s.age<a.minAge)return msg('assetMessage','Too young.');if(s.assets.includes(k))return msg('assetMessage','Already owned.');if(a.type==='cash'){if(s.cash<a.price)return msg('assetMessage','Not enough cash.');s.cash-=a.price}else{if(s.credit===null||s.credit<620)return msg('assetMessage','Credit 620+ required.');const down=Math.round(a.price*.1);if(s.cash<down)return msg('assetMessage',`Need ${money(down)} down.`);s.cash-=down;s.debt+=a.price-down;s.credit-=15}s.assets.push(k);log(`Age ${s.age}: Bought ${a.name}.`);commit()};$('assetButtons').appendChild(b)});
$('dateBtn').onclick=()=>{const ch=(s.looks+s.social+s.happiness)/300;if(Math.random()<ch){s.relationship='Dating';s.relationshipQuality=60;stat('happiness',8);log(`Age ${s.age}: Started dating someone.`);msg('relationshipMessage','You started a relationship.')}else msg('relationshipMessage','No luck this time.');commit()};$('partnerTimeBtn').onclick=()=>{s.relationshipQuality=clamp((s.relationshipQuality||0)+8);stat('happiness',4);stat('stress',-2);commit()};$('marryBtn').onclick=()=>{if(s.relationshipQuality<75)return msg('relationshipMessage','Relationship quality must be 75+.');s.relationship='Married';stat('happiness',10);log(`Age ${s.age}: Got married.`);commit()};$('breakupBtn').onclick=()=>{if(s.relationship==='Single')return;log(`Age ${s.age}: ${s.relationship==='Married'?'Divorced':'Relationship ended'}.`);s.relationship='Single';s.relationshipQuality=null;stat('happiness',-10);commit()};$('childBtn').onclick=()=>{if(Math.random()<.62){const b=person(rn(D.names.children),'Child',0,80);s.family.children.push(b);s.cash-=2500;stat('happiness',10);stat('stress',8);log(`Age ${s.age}: Child ${b.name} was born.`);msg('relationshipMessage',`You welcomed ${b.name}.`)}else msg('relationshipMessage','No child this year.');commit()};$('familyTimeBtn').onclick=()=>{[...s.family.parents,...s.family.siblings].filter(p=>p.alive).forEach(p=>p.quality=clamp(p.quality+5));stat('happiness',4);stat('stress',-2);commit()};$('makeFriendBtn').onclick=()=>{stat('friends',1);stat('social',3);stat('happiness',2);commit()};
$('startBusinessBtn').onclick=()=>{if(s.cash<10000)return msg('businessMessage','Need $10,000.');s.cash-=10000;s.businessLevel=1;s.businessIncome=12000;stat('business',8);stat('stress',8);commit()};$('upgradeBusinessBtn').onclick=()=>{if(s.cash<10000)return msg('businessMessage','Need $10,000.');s.cash-=10000;s.businessLevel++;s.businessIncome=Math.round(s.businessIncome*1.55);stat('business',5);commit()};
[['studyBtn','intelligence',4,'stress',3],['exerciseBtn','fitness',4,'health',2],['socializeBtn','social',4,'happiness',3],['relaxBtn','stress',-7,'happiness',3],['techBtn','technology',5,'intelligence',1],['mechanicalBtn','mechanical',5,'fitness',1],['businessSkillBtn','business',5,'intelligence',1],['creativeBtn','creativity',5,'happiness',2]].forEach(([id,a,x,b,y])=>{$(id).onclick=()=>{stat(a,x);stat(b,y);commit()}});$('crimeBtn').onclick=()=>{stat('karma',-12);const caught=Math.random()<(.25+(50-s.karma)/250);if(caught){s.criminalRecord=true;s.cash=Math.max(0,s.cash-1000);if(s.credit!==null)s.credit=Math.max(300,s.credit-20);stat('stress',12);log(`Age ${s.age}: Caught committing a crime.`);msg('crimeMessage','Caught. Fine and criminal record.')}else{const g=300+Math.random()*1500;s.cash+=g;msg('crimeMessage',`Got away with ${money(g)}.`)}commit()};
$('manualSaveBtn').onclick=()=>save(true);$('exportBtn').onclick=()=>{$('saveBox').value=JSON.stringify(s);msg('saveMessage','Save exported.');};$('importBtn').onclick=()=>{try{s=normalize(JSON.parse($('saveBox').value));msg('saveMessage','Save imported.');commit()}catch{msg('saveMessage','Invalid save data.')}};$('resetBtn').onclick=()=>{if(!confirm('Erase this life?'))return;s=freshState();eventQueue=[];commit()};$('restartAfterDeathBtn').onclick=()=>{s=freshState();eventQueue=[];$('deathOverlay').classList.add('hidden');commit()};
if(!load())s=freshState();$('nameInput').value=s.name;$('genderInput').value=s.gender;$('birthplaceInput').value=s.birthplace;$('backgroundInput').value=s.background;render();save();
})();
